services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      - APP_KEY=base64:zlkX+bn569WwDpw510ArTGUqnWFFqndHrZJ0URdzido=
      - APP_DISABLE_SIGNUP=false
      - DB_HOST=db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=secret
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql